import { useNavigate } from 'react-router-dom';
import { Card, Button, DataTable } from '../components/common';
import { colors, spacing, typography, borderRadius } from '../tokens';

function ReportingCenter() {
  const navigate = useNavigate();

  const reports = [
    { id: 'national', name: 'National Risk Report', description: 'National-level risk overview and statistics', icon: '📊' },
    { id: 'project', name: 'Project Risk Report', description: 'Detailed risk analysis for a specific project', icon: '🏗️' },
    { id: 'sector', name: 'Sector Report', description: 'Risk analysis by sector', icon: '🏢' },
    { id: 'state', name: 'State Report', description: 'Risk analysis by state', icon: '🗺️' },
    { id: 'governance', name: 'Governance Report', description: 'Governance queue and review statistics', icon: '⚖️' },
    { id: 'models', name: 'Model Performance Report', description: 'Experimental ML model metrics', icon: '🤖' },
    { id: 'data-quality', name: 'Data Quality Report', description: 'Data quality and completeness metrics', icon: '💎' },
  ];

  const handleReportClick = (reportId) => {
    if (reportId === 'national') navigate('/reports/national');
    else if (reportId === 'project') navigate('/reports/project');
    else if (reportId === 'sector') navigate('/reports/sector');
    else if (reportId === 'state') navigate('/reports/state');
    else if (reportId === 'governance') navigate('/reports/governance');
    else if (reportId === 'models') navigate('/reports/models');
    else if (reportId === 'data-quality') navigate('/data-health');
  };

  const recentReports = [
    { type: 'National Risk Report', generatedBy: 'admin', generatedAt: '2026-03-15 10:30' },
    { type: 'Governance Report', generatedBy: 'admin', generatedAt: '2026-03-14 15:45' },
    { type: 'Model Performance Report', generatedBy: 'analyst', generatedAt: '2026-03-13 09:15' },
  ];

  const historyColumns = [
    { key: 'type', label: 'Report Type' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'generatedAt', label: 'Generated At' },
    {
      key: 'actions',
      label: 'Actions',
      render: () => (
        <Button variant="ghost" size="sm">Download</Button>
      ),
    },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: spacing.xl }}>
      {/* Report Filters */}
      <Card padding="lg">
        <h3 style={{ marginBottom: spacing.md }}>Report Filters</h3>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(3, 1fr)', 
          gap: spacing.md 
        }}>
          <div>
            <label style={{ 
              display: 'block', 
              fontSize: typography.fontSize.sm, 
              fontWeight: 600,
              color: colors.text.secondary,
              marginBottom: spacing.xs 
            }}>
              Reporting Period
            </label>
            <select
              style={{
                width: '100%',
                padding: `${spacing.sm} ${spacing.md}`,
                backgroundColor: colors.background.primary,
                border: `1px solid ${colors.border.default}`,
                borderRadius: borderRadius.md,
                color: colors.text.primary,
                fontFamily: typography.fontFamily.sans,
                fontSize: typography.fontSize.sm,
              }}
            >
              <option>Last 6 months</option>
              <option>Last 12 months</option>
              <option>Custom range</option>
            </select>
          </div>
          <div>
            <label style={{ 
              display: 'block', 
              fontSize: typography.fontSize.sm, 
              fontWeight: 600,
              color: colors.text.secondary,
              marginBottom: spacing.xs 
            }}>
              Ministry
            </label>
            <select
              style={{
                width: '100%',
                padding: `${spacing.sm} ${spacing.md}`,
                backgroundColor: colors.background.primary,
                border: `1px solid ${colors.border.default}`,
                borderRadius: borderRadius.md,
                color: colors.text.primary,
                fontFamily: typography.fontFamily.sans,
                fontSize: typography.fontSize.sm,
              }}
            >
              <option>All</option>
              <option>Ministry of Road Transport</option>
              <option>Ministry of Railways</option>
              <option>Ministry of Power</option>
            </select>
          </div>
          <div>
            <label style={{ 
              display: 'block', 
              fontSize: typography.fontSize.sm, 
              fontWeight: 600,
              color: colors.text.secondary,
              marginBottom: spacing.xs 
            }}>
              Risk Category
            </label>
            <select
              style={{
                width: '100%',
                padding: `${spacing.sm} ${spacing.md}`,
                backgroundColor: colors.background.primary,
                border: `1px solid ${colors.border.default}`,
                borderRadius: borderRadius.md,
                color: colors.text.primary,
                fontFamily: typography.fontFamily.sans,
                fontSize: typography.fontSize.sm,
              }}
            >
              <option>All</option>
              <option>High and above</option>
              <option>Very High and above</option>
              <option>Critical only</option>
            </select>
          </div>
        </div>
      </Card>

      {/* Report Types */}
      <div style={{ 
        display: 'grid', 
        gridTemplateColumns: 'repeat(3, 1fr)', 
        gap: spacing.lg 
      }}>
        {reports.map((report) => (
          <Card
            key={report.id}
            padding="lg"
            hover={true}
            onClick={() => handleReportClick(report.id)}
            style={{ cursor: 'pointer' }}
          >
            <div style={{ display: 'flex', alignItems: 'center', marginBottom: spacing.md }}>
              <div style={{ 
                width: '48px', 
                height: '48px', 
                backgroundColor: `${colors.accent.primary}10`,
                borderRadius: borderRadius.full,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '1.5rem'
              }}>
                {report.icon}
              </div>
              <div style={{ marginLeft: spacing.md }}>
                <h3 style={{ 
                  fontSize: typography.fontSize.lg,
                  fontWeight: 600,
                  color: colors.text.primary 
                }}>
                  {report.name}
                </h3>
              </div>
            </div>
            <p style={{ 
              fontSize: typography.fontSize.sm,
              color: colors.text.secondary 
            }}>
              {report.description}
            </p>
          </Card>
        ))}
      </div>

      {/* Report History */}
      <Card padding="lg">
        <div style={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'center', 
          marginBottom: spacing.md 
        }}>
          <h3>Recent Reports</h3>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/reports/history')}
          >
            View All History
          </Button>
        </div>
        <DataTable
          data={recentReports}
          columns={historyColumns}
        />
      </Card>
    </div>
  );
}

export default ReportingCenter;
